[features]
seeds = false
[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/home/moderate/.config/solana/id.json"

[programs.devnet]
nft-candy-machine = "2PtNMeZuzXzgabHwG41EeTJL16d5GgTZgNbXaZ5VxZYe"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["nft_candy_machine"]
